### ISSUE TITLE
Practica asterisk

### ISSUE THREAD

**Issue by cafetorres** [UG-Cloud-Computing-2016-Semester1/Practicas#2]
Usuario: 3002
contraseña: 3002
IP del servidor: 52.35.165.42

**Comment by JuanCrg90** [comment]
Te marco

**Comment by JuanCrg90** [comment]
Al parecer si me conecta al *98 pero al marcarte al 3001 me da error, por favor marcame a la cuenta que me estas entregando.

**Comment by cafetorres** [comment]
es que yo soy el 3002

**Comment by JuanCrg90** [comment]
ya me cambie a la 3001, marcame por favor. supongo no quedo claro eso, la información que se entrega es la que se requiere para que yo me conecte

**Comment by JuanCrg90** [comment]
Prueba Realizada con éxito, no se te olvide el reporte.
